import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";

// Transaction interface for admin view
interface AdminTransaction {
  id: string;
  user_email: string;
  amount: number;
  type?: string;
  status: string;
  created_at: string;
  transaction_type: string;
  description: string;
}
import {
  Users,
  FileText,
  TrendingUp,
  CheckCircle,
  XCircle,
  Clock,
  Search,
  Filter,
  Download,
  ThumbsUp,
  ThumbsDown,
  Send,
} from "lucide-react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { StatCard } from "@/components/StatCard";
import { LoanStatusBadge } from "@/components/LoanStatusBadge";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

// PDF Generation Function
const generateDisbursementPDF = async (application: any, adminEmail: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(33, 150, 243);
  doc.text("EduFund - Loan Disbursement Certificate", pageWidth / 2, yPosition, { align: "center" });

  yPosition += 15;
  doc.setDrawColor(33, 150, 243);
  doc.line(20, yPosition, pageWidth - 20, yPosition);

  yPosition += 10;
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);

  // Student Information
  doc.setFont(undefined, "bold");
  doc.text("Student Information", 20, yPosition);
  yPosition += 8;

  doc.setFont(undefined, "normal");
  doc.text(`Name: ${application.student_name}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Email: ${application.student_email}`, 20, yPosition);
  yPosition += 7;
  doc.text(`College: ${application.college}`, 20, yPosition);
  yPosition += 10;

  // Loan Details
  doc.setFont(undefined, "bold");
  doc.text("Loan Details", 20, yPosition);
  yPosition += 8;

  doc.setFont(undefined, "normal");
  doc.text(`Loan ID: ${application.id}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Loan Amount: ₹${application.amount.toLocaleString()}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Purpose: ${application.purpose}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Status: DISBURSED`, 20, yPosition);
  yPosition += 10;

  // Disbursement Information
  doc.setFont(undefined, "bold");
  doc.text("Disbursement Information", 20, yPosition);
  yPosition += 8;

  doc.setFont(undefined, "normal");
  const currentDate = new Date().toLocaleDateString("en-IN");
  doc.text(`Disbursement Date: ${currentDate}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Approved By: Admin (${adminEmail})`, 20, yPosition);
  yPosition += 10;

  // Amount in Words
  doc.setFont(undefined, "bold");
  doc.text("Disbursement Amount (in words):", 20, yPosition);
  yPosition += 7;

  doc.setFont(undefined, "normal");
  const words = numberToWords(application.amount);
  doc.text(`${words} Rupees Only`, 20, yPosition);
  yPosition += 15;

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text("This is an official disbursement certificate generated by EduFund.", pageWidth / 2, pageHeight - 20, { align: "center" });
  doc.text(`Generated on: ${currentDate} | Certificate is valid with digital signature`, pageWidth / 2, pageHeight - 15, { align: "center" });

  return doc;
};

// Helper function to convert numbers to words
const numberToWords = (num: number): string => {
  const ones = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"];
  const teens = ["Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"];
  const tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"];
  const thousands = ["", "Thousand", "Lakh", "Crore"];

  if (num === 0) return "Zero";

  let result = "";
  let groupIndex = 0;

  while (num > 0) {
    const groupValue = num % 1000;
    if (groupValue !== 0) {
      result = convertGroupToWords(groupValue, ones, teens, tens) + " " + thousands[groupIndex] + " " + result;
    }
    num = Math.floor(num / 1000);
    groupIndex++;
  }

  return result.trim();
};

const convertGroupToWords = (num: number, ones: string[], teens: string[], tens: string[]): string => {
  let result = "";
  const hundred = Math.floor(num / 100);
  const remainder = num % 100;

  if (hundred > 0) {
    result += ones[hundred] + " Hundred ";
  }

  if (remainder >= 20) {
    result += tens[Math.floor(remainder / 10)] + " ";
    if (remainder % 10 > 0) {
      result += ones[remainder % 10] + " ";
    }
  } else if (remainder >= 10) {
    result += teens[remainder - 10] + " ";
  } else if (remainder > 0) {
    result += ones[remainder] + " ";
  }

  return result.trim();
};

// Helper function to ensure HTTPS on production
const getApiUrl = () => {
  const baseUrl = import.meta.env.VITE_API_BASE || "http://localhost:4000";
  if (window.location.protocol === 'https:' && baseUrl.startsWith('http://')) {
    return baseUrl.replace('http://', 'https://');
  }
  return baseUrl;
};

interface LoanApplication {
  id: string;
  student_name: string;
  student_email: string;
  college: string;
  amount: number;
  purpose: string;
  status: "pending" | "applied" | "approved" | "rejected" | "disbursed";
  created_at: string;
  tenure_months: number;
}

const mockApplications: LoanApplication[] = [
  {
    id: "1",
    student_name: "John Doe",
    student_email: "john@mit.edu",
    college: "MIT",
    amount: 25000,
    purpose: "Tuition Fees",
    status: "pending",
    created_at: new Date().toISOString(),
    tenure_months: 48,
  },
  {
    id: "2",
    student_name: "Jane Smith",
    student_email: "jane@stanford.edu",
    college: "Stanford",
    amount: 35000,
    purpose: "Study Abroad",
    status: "approved",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    tenure_months: 60,
  },
  {
    id: "3",
    student_name: "Mike Johnson",
    student_email: "mike@harvard.edu",
    college: "Harvard",
    amount: 15000,
    purpose: "Books & Supplies",
    status: "disbursed",
    created_at: new Date(Date.now() - 172800000).toISOString(),
    tenure_months: 24,
  },
];

const AdminDashboard = () => {
  const [user, setUser] = useState<{ email: string } | null>(null);
  const [applications, setApplications] = useState<LoanApplication[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [isLoading, setIsLoading] = useState(true);
  const [confirmDialog, setConfirmDialog] = useState<{ isOpen: boolean; action: "approve" | "reject" | "disburse" | null; loanId: string | null; studentName: string | null }>({ isOpen: false, action: null, loanId: null, studentName: null });
  const [transactions, setTransactions] = useState<AdminTransaction[]>([]);
  const navigate = useNavigate();
  const { toast } = useToast();
  const API_BASE = getApiUrl();

  useEffect(() => {
    const checkAuth = async () => {
      const { data: { session } } = await supabase.auth.getSession();

      if (!session) {
        navigate("/login");
        return;
      }

      // Check if admin
      if (session.user.email !== "edufund0099@gmail.com") {
        navigate("/dashboard");
        return;
      }

      setUser({ email: session.user.email || "" });

      // Fetch real loan applications from API
      await fetchApplications();
    };

    checkAuth();
    fetchTransactions();
  }, [navigate]);

  // Fetch all transactions for admin
  const fetchTransactions = async () => {
    try {
      const response = await fetch(`${API_BASE}/api/transactions`);
      const data = await response.json();
      if (data.ok && data.transactions) {
        setTransactions(data.transactions);
      } else {
        setTransactions([]);
      }
    } catch (err) {
      console.error("Fetch transactions error:", err);
      setTransactions([]);
    }
  };

  const fetchApplications = async () => {
    try {
      const response = await fetch(`${API_BASE}/api/admin/loan-applications`);
      const data = await response.json();

      if (data.ok && data.applications) {
        // Transform the data to match our interface
        const transformed = data.applications.map((app: any) => ({
          id: app.id,
          student_name: app.student_name || "Unknown",
          student_email: app.student_email || "",
          college: app.college || "N/A",
          amount: app.amount || 0,
          purpose: app.reason || "N/A",
          status: app.status || "pending",
          created_at: app.applied_at || app.created_at,
          tenure_months: 48,
        }));
        setApplications(transformed);
      } else {
        setApplications([]);
      }
    } catch (err) {
      console.error("Fetch error:", err);
      toast({
        title: "Error",
        description: "Failed to load loan applications",
        variant: "destructive",
      });
      setApplications([]);
    } finally {
      setIsLoading(false);
    }
  };

  // Show confirmation dialog
  const showConfirmDialog = (action: "approve" | "reject" | "disburse", loanId: string) => {
    const app = applications.find((a) => a.id === loanId);
    setConfirmDialog({
      isOpen: true,
      action,
      loanId,
      studentName: app?.student_name || "Student",
    });
  };

  // Execute action after confirmation
  const executeAction = async () => {
    if (!confirmDialog.loanId) return;

    try {
      console.log('executeAction called with:', confirmDialog.action, confirmDialog.loanId);
      
      switch (confirmDialog.action) {
        case "approve":
          await handleApprove(confirmDialog.loanId);
          break;
        case "reject":
          await handleReject(confirmDialog.loanId);
          break;
        case "disburse":
          await handleDisburse(confirmDialog.loanId);
          break;
      }
    } catch (err) {
      console.error('Error executing action:', err);
    } finally {
      // Always close dialog after execution
      setConfirmDialog({ isOpen: false, action: null, loanId: null, studentName: null });
    }
  };

  const handleApprove = async (id: string) => {
    try {
      const app = applications.find((a) => a.id === id);
      const resp = await fetch(`${API_BASE}/api/update-loan-status`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ loanId: id, status: "approved", studentEmail: app?.student_email }),
      });
      if (!resp.ok) throw new Error("approve failed");
      setApplications((prev) => prev.map((a) => (a.id === id ? { ...a, status: "approved" } : a)));
      
      // Dispatch custom event for real-time update
      window.dispatchEvent(new CustomEvent('loanApproved', { detail: { loanId: id, studentEmail: app?.student_email, amount: app?.amount } }));
      
      toast({ 
        title: "✅ Application Approved", 
        description: `₹${app?.amount.toLocaleString()} approved for ${app?.student_name}. Student has been notified.`,
        variant: "default"
      });
    } catch (err: any) {
      toast({ title: "Approve failed", description: err.message || "Could not approve.", variant: "destructive" });
    }
  };

  const handleReject = async (id: string) => {
    try {
      const app = applications.find((a) => a.id === id);
      const resp = await fetch(`${API_BASE}/api/update-loan-status`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ loanId: id, status: "rejected", studentEmail: app?.student_email }),
      });
      if (!resp.ok) throw new Error("reject failed");
      setApplications((prev) => prev.map((a) => (a.id === id ? { ...a, status: "rejected" } : a)));
      
      // Dispatch custom event for real-time update
      window.dispatchEvent(new CustomEvent('loanRejected', { detail: { loanId: id, studentEmail: app?.student_email } }));
      
      toast({ 
        title: "❌ Application Rejected", 
        description: `Loan application from ${app?.student_name} has been rejected. Student will be notified.`, 
        variant: "destructive" 
      });
    } catch (err: any) {
      toast({ title: "Reject failed", description: err.message || "Could not reject.", variant: "destructive" });
    }
  };

  const handleDisburse = async (id: string) => {
    try {
      const app = applications.find((a) => a.id === id);
      if (!app) throw new Error("Application not found");

      const resp = await fetch(`${API_BASE}/api/update-loan-status`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ loanId: id, status: "disbursed", studentEmail: app.student_email }),
      });
      if (!resp.ok) throw new Error("disburse failed");

      // Generate PDF
      const doc = await generateDisbursementPDF(app, user?.email || "admin@edufund.com");
      
      // Download PDF
      doc.save(`Disbursement_${app.student_name}_${new Date().getTime()}.pdf`);

      setApplications((prev) => prev.map((a) => (a.id === id ? { ...a, status: "disbursed" } : a)));
      
      // Dispatch custom event for real-time update
      window.dispatchEvent(new CustomEvent('loanDisbursed', { detail: { loanId: id, studentEmail: app.student_email, amount: app.amount } }));
      
      toast({ 
        title: "✅ Money Disbursed Successfully!", 
        description: `₹${app.amount.toLocaleString()} has been approved and transferred to ${app.student_name}. Disbursement certificate PDF has been downloaded.`,
        variant: "default"
      });
    } catch (err: any) {
      toast({ title: "Disburse failed", description: err.message || "Could not mark disbursed.", variant: "destructive" });
    }
  };

  const filteredApplications = applications.filter((app) => {
    const matchesSearch =
      app.student_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      app.student_email.toLowerCase().includes(searchQuery.toLowerCase()) ||
      app.college.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = statusFilter === "all" || app.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const stats = {
    totalApplications: applications.length,
    pending: applications.filter((a) => a.status === "pending").length,
    approved: applications.filter((a) => a.status === "approved").length,
    totalDisbursed: applications
      .filter((a) => a.status === "disbursed")
      .reduce((sum, a) => sum + a.amount, 0),
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      minimumFractionDigits: 0,
    }).format(value);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="animate-pulse flex flex-col items-center gap-4">
          <div className="h-12 w-12 rounded-full bg-primary/20" />
          <p className="text-muted-foreground">Loading...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Header user={user} isAdmin />

      <main className="container mx-auto px-4 py-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <h1 className="text-2xl md:text-3xl font-bold text-foreground mb-2">
            Admin Dashboard
          </h1>
          <p className="text-muted-foreground">
            Manage loan applications and student records
          </p>
        </motion.div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <StatCard
            icon={FileText}
            label="Total Applications"
            value={stats.totalApplications}
            delay={0}
          />
          <StatCard
            icon={Clock}
            label="Pending Review"
            value={stats.pending}
            delay={0.1}
          />
          <StatCard
            icon={CheckCircle}
            label="Approved"
            value={stats.approved}
            delay={0.2}
          />
          <StatCard
            icon={TrendingUp}
            label="Total Disbursed"
            value={formatCurrency(stats.totalDisbursed)}
            delay={0.3}
          />
        </div>

        {/* Applications Table */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          <Card className="card-elevated">
            <CardHeader>
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <CardTitle>Loan Applications</CardTitle>
                <div className="flex flex-col sm:flex-row gap-3">
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <Input
                      placeholder="Search students..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      className="pl-9 w-full sm:w-64"
                    />
                  </div>
                  <Select value={statusFilter} onValueChange={setStatusFilter}>
                    <SelectTrigger className="w-full sm:w-40">
                      <Filter className="h-4 w-4 mr-2" />
                      <SelectValue placeholder="Filter" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Status</SelectItem>
                      <SelectItem value="pending">Pending</SelectItem>
                      <SelectItem value="approved">Approved</SelectItem>
                      <SelectItem value="rejected">Rejected</SelectItem>
                      <SelectItem value="disbursed">Disbursed</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">
                        Student
                      </th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">
                        College
                      </th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">
                        Amount
                      </th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">
                        Purpose
                      </th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">
                        Status
                      </th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">
                        Approve
                      </th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">
                        Reject
                      </th>
                      <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">
                        Disburse
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredApplications.map((app) => (
                      <tr
                        key={app.id}
                        className="border-b border-border hover:bg-muted/50 transition-colors"
                      >
                        <td className="py-4 px-4">
                          <div>
                            <p className="font-medium text-foreground">
                              {app.student_name}
                            </p>
                            <p className="text-sm text-muted-foreground">
                              {app.student_email}
                            </p>
                          </div>
                        </td>
                        <td className="py-4 px-4 text-sm">{app.college}</td>
                        <td className="py-4 px-4 font-medium">
                          {formatCurrency(app.amount)}
                        </td>
                        <td className="py-4 px-4 text-sm">{app.purpose}</td>
                        <td className="py-4 px-4">
                          <LoanStatusBadge status={app.status} />
                        </td>
                        <td className="py-4 px-4">
                          <button
                            onClick={() => {
                              alert(`✅ Approving loan for ${app.student_name}`);
                              console.log('Approve clicked:', app.id, app.student_email);
                              showConfirmDialog('approve', app.id);
                            }}
                            onMouseEnter={(e) => {
                              (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1.1)';
                              (e.currentTarget as HTMLButtonElement).style.cursor = 'pointer';
                            }}
                            onMouseLeave={(e) => {
                              (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1)';
                              (e.currentTarget as HTMLButtonElement).style.cursor = 'pointer';
                            }}
                            style={{ cursor: 'pointer' }}
                            className="w-12 h-12 rounded-full flex items-center justify-center transition-all bg-green-100 text-green-600 hover:bg-green-200 hover:shadow-lg"
                            title="Approve"
                            type="button"
                          >
                            <ThumbsUp className="h-6 w-6" />
                          </button>
                        </td>
                        <td className="py-4 px-4">
                          <button
                            onClick={() => {
                              alert(`❌ Rejecting loan for ${app.student_name}`);
                              console.log('Reject clicked:', app.id, app.student_email);
                              showConfirmDialog('reject', app.id);
                            }}
                            onMouseEnter={(e) => {
                              (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1.1)';
                              (e.currentTarget as HTMLButtonElement).style.cursor = 'pointer';
                            }}
                            onMouseLeave={(e) => {
                              (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1)';
                              (e.currentTarget as HTMLButtonElement).style.cursor = 'pointer';
                            }}
                            style={{ cursor: 'pointer' }}
                            className="w-12 h-12 rounded-full flex items-center justify-center transition-all bg-red-100 text-red-600 hover:bg-red-200 hover:shadow-lg"
                            title="Reject"
                            type="button"
                          >
                            <ThumbsDown className="h-6 w-6" />
                          </button>
                        </td>
                        <td className="py-4 px-4">
                          <button
                            onClick={() => {
                              alert(`💰 Disbursing loan for ${app.student_name}`);
                              console.log('Disburse clicked:', app.id, app.student_email);
                              showConfirmDialog('disburse', app.id);
                            }}
                            onMouseEnter={(e) => {
                              (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1.1)';
                              (e.currentTarget as HTMLButtonElement).style.cursor = 'pointer';
                            }}
                            onMouseLeave={(e) => {
                              (e.currentTarget as HTMLButtonElement).style.transform = 'scale(1)';
                              (e.currentTarget as HTMLButtonElement).style.cursor = 'pointer';
                            }}
                            style={{ cursor: 'pointer' }}
                            className="w-12 h-12 rounded-full flex items-center justify-center transition-all bg-blue-100 text-blue-600 hover:bg-blue-200 hover:shadow-lg"
                            title="Disburse"
                            type="button"
                          >
                            <Send className="h-6 w-6" />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>

                {filteredApplications.length === 0 && (
                  <div className="text-center py-12">
                    <FileText className="h-12 w-12 text-muted-foreground/50 mx-auto mb-4" />
                    <p className="text-muted-foreground">No applications found</p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Transaction History */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mt-8"
        >
          <Card className="card-elevated">
            <CardHeader>
              <CardTitle>Transaction History</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="max-h-[600px] overflow-y-auto">
                {transactions && transactions.length > 0 ? (
                  <div className="space-y-3">
                    {transactions.map((tx: AdminTransaction) => (
                      <motion.div
                        key={tx.id}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="flex items-center justify-between p-4 bg-muted/50 rounded-lg hover:bg-muted/70 transition-colors border-l-4 border-blue-500"
                      >
                        <div className="flex-1">
                          <p className="font-medium text-sm">
                            {tx.user_email}
                          </p>
                          <p className="text-xs text-muted-foreground capitalize">
                            {tx.transaction_type}
                          </p>
                          <p className="text-xs text-muted-foreground mt-1">
                            {new Date(tx.created_at).toLocaleDateString('en-IN', { 
                              day: '2-digit', 
                              month: 'short', 
                              year: 'numeric',
                              hour: '2-digit',
                              minute: '2-digit'
                            })}
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="font-semibold text-sm text-green-600">
                            ₹{tx.amount.toLocaleString('en-IN')}
                          </p>
                          <p className="text-xs text-muted-foreground mt-1">
                            {tx.status}
                          </p>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    <p>No transactions yet</p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </main>

      {/* Confirmation Dialog */}
      <AlertDialog open={confirmDialog.isOpen} onOpenChange={(isOpen) => !isOpen && setConfirmDialog({ isOpen: false, action: null, loanId: null, studentName: null })}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Confirm Action</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to <strong>{confirmDialog.action}</strong> the loan application for <strong>{confirmDialog.studentName}</strong>? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="flex gap-3 justify-end">
            <AlertDialogCancel onClick={() => {
              console.log('Cancel clicked');
              setConfirmDialog({ isOpen: false, action: null, loanId: null, studentName: null });
            }}>Cancel</AlertDialogCancel>
            <Button 
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                console.log('Confirm clicked, executing action:', confirmDialog.action);
                executeAction();
              }}
              className="bg-green-600 hover:bg-green-700 text-white"
            >
              {confirmDialog.action === "approve" && "✅ Approve"}
              {confirmDialog.action === "reject" && "❌ Reject"}
              {confirmDialog.action === "disburse" && "💰 Disburse"}
            </Button>
          </div>
        </AlertDialogContent>
      </AlertDialog>

      <Footer />
    </div>
  );
};

export default AdminDashboard;
